#!/usr/bin/python
# -*- coding: UTF-8 -*-
#

from __future__ import absolute_import, print_function, unicode_literals

import dbus
import sys
import time

bus = dbus.SystemBus()
manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
modems = manager.GetModems()

for path, props in modems:
	# print("[ %s ]" % path)
	if 'org.ofono.VoiceCallManager' not in props['Interfaces']:
		continue
	
	mgr = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.VoiceCallManager')
	calls = mgr.GetCalls()

	for path, props in calls:
		state = props['State']
		print("[ %s ] %s" % (path, state))

		if state != "incoming":
			continue
		call = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.VoiceCall')
		call.Answer()
		break


