#!/usr/bin/python

from __future__ import absolute_import, print_function, unicode_literals

import dbus
import dbus.mainloop.glib
try:
  from gi.repository import GObject
except ImportError:
  import gobject as GObject


import bluezutils


relevant_ifaces = [ "org.bluez.Adapter1", "org.bluez.Device1" ]

def property_changed(interface, changed, invalidated, path):
	print("Property_changed")
	print(changed)
	props = ['Powered', 'Discoverable', 'Discovering']
	for key in changed.keys():
		if key not in props:
			continue
		print("%s: %s" % (key, changed[key]))

	if 'RSSI' in changed:
		devices[path] = dict(devices[path].items() + 
								changed.items())
		print("RSSI: %s, %s" % (devices[path]['Address'], 
					devices[path]['RSSI']))
	
	print(" ")

def interfaces_added(path, interfaces):
	print("interfaces_added")
	if 'org.bluez.Device1' not in interfaces:
		return
	if path not in devices:
		devices[path] = interfaces['org.bluez.Device1']
		
	print("NewDevice: %s, %s" % (devices[path]['Address'], 
				devices[path]['Alias']))
	print(" ")

def interfaces_removed(path, interfaces):
	print("interfaces_removed")
	address = devices[path]['Address']
	Name = devices[path]['Alias']
	print("DelDevice: %s, %s" % (address, Name))

	print(" ")

if __name__ == '__main__':
	dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

	bus = dbus.SystemBus()

	bus.add_signal_receiver(property_changed, bus_name="org.bluez",
			dbus_interface="org.freedesktop.DBus.Properties",
			signal_name="PropertiesChanged",
			path_keyword="path")

	bus.add_signal_receiver(interfaces_added, bus_name="org.bluez",
			dbus_interface="org.freedesktop.DBus.ObjectManager",
			signal_name="InterfacesAdded")

	bus.add_signal_receiver(interfaces_removed, bus_name="org.bluez",
			dbus_interface="org.freedesktop.DBus.ObjectManager",
			signal_name="InterfacesRemoved")

	# get managed objects 
	devices = {}
	mo = bluezutils.get_managed_objects()
	for path, interfaces in mo.iteritems():
		if 'org.bluez.Device1' in interfaces:
			devices[path] = interfaces['org.bluez.Device1']


	mainloop = GObject.MainLoop()
	mainloop.run()
