#!/usr/bin/python

from __future__ import absolute_import, print_function, unicode_literals

import dbus
import dbus.mainloop.glib
try:
  from gi.repository import GObject
except ImportError:
  import gobject as GObject

import re
import bluezutils

# Environment LANG=en_GB.UTF-8

prop_interfaces = ['org.bluez.Adapter1', 'org.bluez.MediaPlayer1',
					'org.bluez.Device1']
props = ['Powered', 'Discoverable', 'Discovering', 'Status']

def property_changed(interface, changed, invalidated, path):
	if interface not in prop_interfaces:
		return
	# print("Property_changed")
	# print(changed)
	for key in changed.keys():
		if key not in props:
			continue
		print("%s: %s" % (key, changed[key]))

	if 'RSSI' in changed:
		pat = re.compile(r'/.*/hci\d/dev_(.*)')
		m = pat.search(path)
		add = m.group(1).replace('_', ':')
		print("RSSI: %s, %s" % (add, changed['RSSI']))
	
	# print(" ")

def interfaces_added(path, interfaces):
	# print("interfaces_added")
	if 'org.bluez.Device1' not in interfaces:
		return
	if path not in devices:
		devices[path] = interfaces['org.bluez.Device1']
		
	print("NewDevice: %s, %s" % (devices[path]['Address'], 
				devices[path]['Alias']))
	# print(" ")

def interfaces_removed(path, interfaces):
	# print("interfaces_removed")
	if path not in devices:
		return
	address = devices[path]['Address']
	Name = devices[path]['Alias']
	print("DelDevice: %s, %s" % (address, Name))

	# print(" ")

if __name__ == '__main__':
	dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

	bus = dbus.SystemBus()

	bus.add_signal_receiver(property_changed, bus_name="org.bluez",
			dbus_interface="org.freedesktop.DBus.Properties",
			signal_name="PropertiesChanged",
			path_keyword="path")

	bus.add_signal_receiver(interfaces_added, bus_name="org.bluez",
			dbus_interface="org.freedesktop.DBus.ObjectManager",
			signal_name="InterfacesAdded")

	bus.add_signal_receiver(interfaces_removed, bus_name="org.bluez",
			dbus_interface="org.freedesktop.DBus.ObjectManager",
			signal_name="InterfacesRemoved")

	# get managed objects 
	devices = {}
	mo = bluezutils.get_managed_objects()
	for path, interfaces in mo.iteritems():
		if 'org.bluez.Device1' in interfaces:
			devices[path] = interfaces['org.bluez.Device1']


	mainloop = GObject.MainLoop()
	mainloop.run()
