#!/usr/bin/python
# -*- coding: UTF-8 -*-
#

from __future__ import absolute_import, print_function, unicode_literals

import argparse
import dbus
import sys
import time

# hangup all call, state = incoming/active

bus = dbus.SystemBus()
manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
modems = manager.GetModems()

for path, props in modems:
	if 'org.ofono.VoiceCallManager' not in props['Interfaces']:
		continue

	m = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.VoiceCallManager')
	m.HangupAll()
	break


