#!/usr/bin/python

from __future__ import absolute_import, print_function, unicode_literals

# from optparse import OptionParser, make_option
import argparse
import dbus
import dbus.mainloop.glib
try:
  from gi.repository import GObject
except ImportError:
  import gobject as GObject
import bluezutils

import os
import socket
import sys
import time

if __name__ == '__main__':
	parser = argparse.ArgumentParser()
	parser.add_argument("-t", "--timeout", type=int, \
			default=180, help="Set timeout for bluetooth scan opt")
	args = parser.parse_args()
	print(args)

	bus = dbus.SystemBus()
	adapter = bluezutils.find_adapter()
	
	adapter.StartDiscovery()
	print("Start Discovery")

	try:
		time.sleep(args.timeout)
	# stop scan: killall -SIGINT bt-scan-4
	except KeyboardInterrupt:
		print("Keyboard Interrupt")
	finally:
		adapter.StopDiscovery()
		print("Stop Discovery")

